repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-merge-conflict
          - id: check-yaml
          - id: detect-private-key
          - id: end-of-file-fixer
            exclude: '.*\.ipynb'
          - id: trailing-whitespace
    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black-jupyter
    - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
      rev: v0.1.0
      hooks:
          - id: dockerfilelint
    - repo: https://github.com/nbQA-dev/nbQA
      rev: 1.3.1
      hooks:
          - id: nbqa-check-ast
          - id: nbqa-flake8
          - id: nbqa-isort
          - id: nbqa-pyupgrade
            args:
                - --py39-plus
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.7.1
      hooks:
          - id: prettier
            args:
                - --config-precedence=file-override
    - repo: https://github.com/kynan/nbstripout
      rev: 0.5.0
      hooks:
          - id: nbstripout
    - repo: meta
      hooks:
          - id: check-hooks-apply
          - id: check-useless-excludes
