name: aibv

channels:
    - conda-forge
    - maxiv

dependencies:
    - black-jupyter>=22.3.0,<23.0.0
    - flake8>=4.0.1,<5.0.0
    - ipykernel>=6.13.1,<7.0.0
    - ipywidgets>=7.7.0,<8.0.0
    - isort>=5.10.1,<6.0.0
    - matplotlib>=3.5.2,<4.0.0
    - maxiv:pypylon>=1.8.0,<2.0.0
    - nbqa>=1.3.1,<2.0.0
    - nbstripout>=0.5.0,<1.0.0
    - opencv>=4.5.5,<5.0.0
    - pandas>=1.4.2,<2.0.0
    - pre-commit>=2.19.0,<3.0.0
    - python>=3.9,<3.10
    - pyupgrade>=2.34.0,<3.0.0
    - scikit-learn>=1.1.1,<2.0.0
    - tensorflow>=2.8.1,<3.0.0
