name: aibv

channels:
  - conda-forge
  - maxiv

dependencies:
  - ipykernel>=6.10.0,<7.0.0
  - ipywidgets>=7.7.0,<8.0.0
  - matplotlib>=3.5.1,<4.0.0
  - maxiv:pypylon>=1.8.0,<2.0.0
  - nbstripout>=0.5.0,<1.0.0
  - opencv>=4.5.5,<5.0.0
  - pre-commit>=2.17.0,<3.0.0
  - python>=3.9,<3.10
  - tensorflow>=2.7.0,<3.0.0
